### ISSUE TITLE
求助，经常会出现这种报错如何解决

### ISSUE THREAD

**Issue by zxj1009587922** [azureqaq/tjuptatt_release#1]
在进行top10签到时
时常会出现“error sending request for url (https://www.tjupt.org/attendance.php): operation timed out, 尝试普通签到”
先前以为是开了代理的原因
关了代理运行仍会出现这样子的报错
想问问大佬如何解决呀
最后拜谢大佬的top10软件

**Comment by azureqaq** [comment]
首先，非常感谢对这个小项目的认可以及愿意反馈遇到的问题。
因为 [TJUPT](https://tjupt.org/) 的服务器在国外，不佳的网络情况下确实很容易出现这种情况，遗憾的是目前没有什么好的解决方案。不过可以尝试以下方法来缓解

经过我的测试，在tju的教育网络下较少出现这种情况

## 测试方法
1. 可以 [在线查看各地延迟](https://www.itdog.cn/ping/tjupt.org)
2. 通过 windows-cmd: `ping tjupt.org` 来查看本地与 *TJUPT* 服务器的连接情况 *以下为我所在的非tju教育网下的结果，可以看到网络连接并不通畅*
    > ```cmd
    > ping tjupt.org
    > 
    > 正在 Ping tjupt.org [172.64.106.12] 具有 32 字节的数据:
    > 请求超时。
    > 来自 172.64.106.12 的回复: 字节=32 时间=223ms TTL=51
    > 来自 172.64.106.12 的回复: 字节=32 时间=213ms TTL=51
    > 来自 172.64.106.12 的回复: 字节=32 时间=213ms TTL=51
    > 
    > 172.64.106.12 的 Ping 统计信息:
    >     数据包: 已发送 = 4，已接收 = 3，丢失 = 1 (25% 丢失)，
    > 往返行程的估计时间(以毫秒为单位):
    > 最短 = 213ms，最长 = 223ms，平均 = 216ms
    > ```

## 如何缓解
1. 适当增加重试次数
    - 对于临时使用: `tjuptatt -u USERNAME PASSWORD -r RETRY_TIMES` 来指定重试次数
    - 对于配置文件（可选TOP 10）：参考 [配置文件模板](./config_template.toml) 填写或修改 `retry` 字段 *现在已经上传了配置模板*
        - 配置文件路径可通过观察 `tjuptatt -h` 中 `--file` 的默认值获得
2. 在以后的版本中可能适当增加“超时”的限制，或提供配置方法

## 一些其他提醒
- 受限于豆瓣API，这个软件的成功率并不高，或者启用邮件通知功能，在签到失败时提醒手动签到
- 在不佳的网络情况下，TOP 10 签到很难达成
- 断签情况需要手动操作
- 这个软件是为了学习 `Rust` 来练手的，其实更适合用 `Python` 来写，没有什么技术含量，肯定称不上大佬这个称呼的

**Comment by azureqaq** [comment]
@zxj1009587922 已增加配置文件选项（版本号: [v0.1.3](https://github.com/azureqaq/tjuptatt_release/releases/tag/v0.1.3)） `network.timeout` 详细使用方式请查看配置文件模板。
这样可以减少此类错误的出现，但是对于TOP10签到帮助不大

**Comment by zxj1009587922** [comment]
谢谢谢谢谢谢谢
感谢大佬的详细解释（拜谢.jpg
