### ISSUE TITLE
如何使用保存好的cookie进行登录

### ISSUE THREAD

**Issue by zxj1009587922** [azureqaq/tjuptatt_release#2]
近期北洋园关闭游客访问了
只能通过保存下来的cookie进行登录
不知大佬的程序能否使用保存在浏览器/文件夹内的cookie信息进行签到呢

**Comment by azureqaq** [comment]
@zxj1009587922 你好，tjuptatt **支持自定义cookies**

**注意:** 仅支持 *通过配置文件签到* 模式

在 `--top` 模式下，为了提高签到速度，默认保存了cookies

## 提取浏览器cookies
**注意:** 由于目前手边没有windows的机器，所以一部分内容是按照我的印象写的回答，请酌情参考

1. 找到本地保存的cookies文件：在资源管理器的地址栏输入 `%APPDATA%` 回车，此时所在路径(暂时称为路径1)应该可以看到文件夹 `tjuptatt`，在路径1的上一层级，可以看到还有另外两个文件夹，其中一个文件夹中也包括 `tjuptatt` 文件夹，其中应该包括一个 `json` 文件，命名格式为 `USERNAME_cookies.json` 用 `utf-8` 格式打开(注意：如果是win10或更老的系统版本请不要用自带的记事本打开，可以用 notepad3 或其他支持 `utf-8` 编码的文本编辑器。否则可能会出现程序无法读取cookies的情况)
2. 假设你使用的edge浏览器，按照 [Edge的官方文档](https://learn.microsoft.com/zh-cn/microsoft-edge/devtools-guide-chromium/storage/cookies) 来进行提取cookies操作。`json` 文件格式为键值对的形式: `{ "key1": value1, "key2": value2}`，请按照第一步中获得的数据，在edge中查找需要的键，并更新本地文件中对应的值
3. 如果，并没找到 `USERNAME_cookies.json` 文件，请回复我，我会在空闲时间给你一份模版
4. 如果你使用过 `--top` 模式，那么应该会有这样一个cookies文件

## 拜托你信得过的人，在tju教育网下用 tjuptatt 的配置文件模式签到一次
1. 如何用 *配置文件模式* 签到请查看 [README.md](https://github.com/azureqaq/tjuptatt_release/blob/master/README.md)
2. 在tju网络下签到过后，将上文中提到的 `USERNAM_cookies.json` 替换自己电脑中的文件
3. 此方法获得的cookies有效期 **只有7天**


如果有其他问题欢迎继续提问

**Comment by zxj1009587922** [comment]
> 

是的是的，我已找到该json。
Windows的路径为：C:\Users\"用户名"\AppData\Local\tjuptatt。
但json中有一些我难以匹配的上的数据还请大大指教。

从edge中利用插件导出的json格式如下：【记为A】
[
{
    "domain": ".tjupt.org",
    "expirationDate": 1710576922,
    "hostOnly": false,
    "httpOnly": false,
    "name": "access_token",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": cookie_value,
    "isProtected": true,
    "id": 1
}
]

而本地中json中的数据格式为【记为B】
{"raw_cookie":"bid=bMoNPNelnag; Path=/; Domain=douban.com; Expires=Sat, 06 Jan 2024 04:15:56 GMT","path":["/",true],"domain":{"Suffix":"douban.com"},"expires":{"AtUtc":"2024-01-06T04:15:56Z"}}【设定为part1】
{"raw_cookie":"access_token=cookie_value;
Path=/;
Domain=tjupt.org;
Max-Age=604800;
Expires=Fri, 13 Jan 2023 04:15:54 GMT","path":["/",true],"domain":{"Suffix":"tjupt.org"},"expires":{"AtUtc":"2023-01-13T04:15:59Z"}}【设定为part2】
part1的数据我猜测应该是douban的cookie，和tjupt无关
而part2的数据则和edge导出的数据无法一一对应，请大大指教（除cookie_value可明确对应上）

而我根据时间关系有一个待求证的对应关系
A中的“expirationDate”和B中的Expires对应，因为A中的"expirationDate": 1710576922是时间戳转换为日期则是2024-03-16 16:15:22，其格式与B中的Expires相同
B中的Max-Age=604800;应该表明其有效期，因为转换为时间戳则刚好为7天。

不知上述猜测是否准确，若有缺漏之处还请大大指教。
拜谢.jpg

**Comment by azureqaq** [comment]
@zxj1009587922 你好，首先非常感谢你提出的建议，对我非常有用，你的猜测在我的认知里是很准的。
我犯了个错误，在tju网络下也无法登录，之前一直认为在tju网络下可以登录。所以只能通过修改已有cookie的方式继续使用了。

由你提供的数据

浏览器提取的cookie：

```json
{
	"domain": ".tjupt.org",
	"expirationDate": 1710576922,
	"hostOnly": false,
	"httpOnly": false,
	"name": "access_token",
	"path": "/",
	"sameSite": "unspecified",
	"secure": false,
	"session": false,
	"storeId": "0",
	"value": "cookie_value",
	"isProtected": true,
	"id": 1
}
```

本地保存的cookies：

```json
{
	"raw_cookie": "access_token=cookie_value;Path=/;Domain=tjupt.org;Max-Age=604800;Expires=Fri, 13 Jan 2023 04:15:54 GMT",
	"path": ["/", true],
	"domain": {
		"Suffix": "tjupt.org"
	},
	"expires": {
		"AtUtc": "2023-01-13T04:15:59Z"
	}
}
```

> raw_cookie: 原始cookie
>
> Max-Age: 有效时间
>
> Expires: 到何时cookie过期

和浏览器插件提取的cookie不同，我 **猜测** 可能是因为：我所使用的 `Rust` 库 `reqwests_cookie_store`  储存的格式问题，它经过了一些变形来 储存/读取 的。

cookie 结构：

> 1. 用抓包工具 fidller 只能看到 cookie 的 name 和 value 两个参数，实际上 cookie 还有其它参数
>
> 2. 以下是一个完整的 cookie 组成结构 
>
>    cookie ={u'domain': u'.cnblogs.com', u'name': u'.CNBlogsCookie', u'value': u'xxxx', u'expiry': 1491887887, u'path': u'/', u'httpOnly': True, u'secure': False} 
>
>    name：cookie 的名称 
>
>    value：cookie 对应的值，动态生成的 
>
>    domain：服务器域名 
>
>    expiry：Cookie 有效终止日期 
>
>    path：Path 属性定义了 Web 服务器上哪些路径下的页面可获取服务器设置的 Cookie 
>
>    httpOnly：防脚本攻击 
>
>    secure:在 Cookie 中标记该变量，表明只有当浏览器和 Web Server 之间的通信协议为加密 认证协议时， 浏览器才向服务器提交相应的 Cookie。当前这种协议只有一种，即为 HTTPS。
>
> [cookie 组成结构 - 灬菜鸟灬 - 博客园 (cnblogs.com)](https://www.cnblogs.com/wu-wu/p/10537674.html)

浏览器中提取的cookie数据，有一部分是本程序不需要的，可以忽略

真正需要修改的是：`AtUtc` 以及 `raw_cookie` 中的 `access_token` `Expires` `Max-Age` (可选)

我对cookie的机制并不是很了解，不清楚 `cookie_value` 和 `expires` 对于 tjupt 来说是否互不影响，如果你修改后能够使用，那么就是互不影响

通过浏览器修改的cookies来更新本地cookie：

1. 本地中 `AtUtc` 要按照格式，设定为想要的日期，比如：`2023-01-23T04:15:59Z`
2. 按照 `AtUtc` 更新 `raw_cookie` 中的 `Expires` (*再减去5秒？*)

非常抱歉，我现在无法实际测试一下。再次感谢你提出的建议。

**Comment by zxj1009587922** [comment]
根据原cookie数据的日期和EditThisCookie插件修改后的时间进行推断
Time_0：Sat Feb 17 2023 10:45:46 GMT+0800，为浏览器使用EditThisCookie修改时的时间
Time_1：Sun Mar 17 2024 10:45:46 GMT+0800，为浏览器EditThisCookie修改后最长有效时间
Time_2：2023-01-13T04:15:59Z，为原cookie中的expires，格式为"expires":{"AtUtc":"2023-01-13T04:15:59Z"}
Time_3：Fri, 13 Jan 2023 04:15:54 GMT，为原cookie中的raw_cookie所带的Expires，格式为Max-Age=604800; Expires=Fri, 13 Jan 2023 04:15:54 GMT"

根据四个时间进行推断，有一个猜想：
Time_2和Time_3只是不同表达方式的相同时间，而Time_3所带的Max-Age为有效期
那么若使用EditThisCookie修改后有效时间，则修改后的本地cookie中的expires和raw_cookie中的Expires应分别为2024-03-17T02:45:46.160Z和Sun Mar 17 2024 02:45:46 GMT【因为EditThisCookie修改的cookie的时区为东八区（从GMT+0800可得）而原cookie的时区为格林威治时间，因此比EditThisCookie修改的时间少8小时】。
在对Time_0和Time_1比较时发现，EditThisCookie可修改的最长有效时间为一年零一个月，换算为时间戳则为34185600，即对应raw_cookie中的Max-Age

此外我查询了一些相关的资料，若同时存在Max-Age和Expires，首先生效的是Max-Age，因此Max-Age并不是可选的修改项，而是必选的修改项
附上链接和截图：
[cookie属性max-age与expires同时存在时谁会生效](https://blog.csdn.net/feinifi/article/details/116448186)
![image](https://user-images.githubusercontent.com/60542924/218236595-187bf2f2-acb5-4e76-ab7d-074a18ee71c3.png)

我已按照上述所做的推想完成cookie的修改，并将在即将到来的12点top签到时间进行验证，若验证成功也在此issue下进行补充。感谢大大的详细解答。
若仍有问题还望大大不吝赐教。

**Comment by azureqaq** [comment]
@zxj1009587922 感谢你提供的详细信息，让我学到了一些新东西。
如果有什么建议欢迎继续交流，相互学习。

**Comment by zxj1009587922** [comment]
很可惜
尝试了一天的top登录之后，仍未完成签到（一共三次，12时、18时、20时）
但个人认为出现了operation timed out的错误则表示该cookie成功有效【但在此过程中出现了一个往常未曾出现过的错误（登陆失败，请检查账号/密码, 尝试普通签到），详见后文】

附上log（隐去了真实用户名，以“用户名”代替）
DEBUG [libs::user] “用户名” 选择的签到时间为: 2023-02-11 6:00:00.0 +08:00:00
DEBUG [libs::user] 总共还需等待: 52s660ms380??s800ns
DEBUG [libs::user] 距离登录还需要: 46s640ms380??s800ns
DEBUG [libs::user] 距离获取答案: 2s997ms478??s900ns
WARN  [libs::user] “用户名” 无法top10签到, Err: error sending request for url (https://www.tjupt.org/attendance.php): operation timed out, 尝试普通签到
DEBUG [libs::user] “用户名” 签到失败, 1/1, Err: 登陆失败, 请检查账号/密码
ERROR [tjuptatt] Error: top10 try 所有尝试都失败了
DEBUG [libs::user] “用户名” 选择的签到时间为: 2023-02-11 7:00:00.0 +08:00:00
DEBUG [libs::user] 总共还需等待: 51s961ms820??s
DEBUG [libs::user] 距离登录还需要: 45s941ms820??s
DEBUG [libs::user] 距离获取答案: 2s982ms715??s100ns
WARN  [libs::user] “用户名” 无法top10签到, Err: error sending request for url (https://www.tjupt.org/attendance.php): operation timed out, 尝试普通签到
DEBUG [libs::user] “用户名” 签到失败, 1/1, Err: error sending request for url (https://www.tjupt.org/attendance.php): operation timed out
ERROR [tjuptatt] Error: top10 try 所有尝试都失败了
DEBUG [libs::user] “用户名” 选择的签到时间为: 2023-02-11 8:00:00.0 +08:00:00
DEBUG [libs::user] 总共还需等待: 58s642ms983??s600ns
DEBUG [libs::user] 距离登录还需要: 52s622ms983??s600ns
DEBUG [libs::user] 距离获取答案: 2s998ms72??s600ns
WARN  [libs::user] “用户名” 无法top10签到, Err: 登陆失败, 请检查账号/密码, 尝试普通签到
DEBUG [libs::user] “用户名” 签到失败, 1/1, Err: 登陆失败, 请检查账号/密码
ERROR [tjuptatt] Error: top10 try 所有尝试都失败了
DEBUG [libs::user] “用户名” 选择的签到时间为: 2023-02-11 12:00:00.0 +08:00:00
DEBUG [libs::user] 总共还需等待: 53s380ms157??s500ns
DEBUG [libs::user] 距离登录还需要: 47s360ms157??s500ns
DEBUG [libs::user] 距离获取答案: 2s986ms203??s700ns
WARN  [libs::user] “用户名” 无法top10签到, Err: 请检查pt服务器状态, 尝试普通签到
DEBUG [libs::user] “用户名” 签到失败, 1/1, Err: 请检查pt服务器状态
ERROR [tjuptatt] Error: top10 try 所有尝试都失败了
DEBUG [libs::user] “用户名” 选择的签到时间为: 2023-02-11 18:00:00.0 +08:00:00
DEBUG [libs::user] 总共还需等待: 58s303ms500??s700ns
DEBUG [libs::user] 距离登录还需要: 52s283ms500??s700ns
DEBUG [libs::user] 距离获取答案: 2s989ms532??s100ns
WARN  [libs::user] “用户名” 无法top10签到, Err: 登陆失败, 请检查账号/密码, 尝试普通签到
DEBUG [libs::user] “用户名” 签到失败, 1/1, Err: 登陆失败, 请检查账号/密码
ERROR [tjuptatt] Error: top10 try 所有尝试都失败了
DEBUG [libs::user] “用户名” 选择的签到时间为: 2023-02-11 20:00:00.0 +08:00:00
DEBUG [libs::user] 总共还需等待: 58s239ms235??s600ns
DEBUG [libs::user] 距离登录还需要: 52s219ms235??s600ns
DEBUG [libs::user] 距离获取答案: 2s997ms668??s500ns
WARN  [libs::user] “用户名” 无法top10签到, Err: error sending request for url (https://www.tjupt.org/attendance.php): operation timed out, 尝试普通签到
DEBUG [libs::user] “用户名” 签到失败, 1/1, Err: error sending request for url (https://www.tjupt.org/attendance.php): operation timed out
ERROR [tjuptatt] Error: top10 try 所有尝试都失败了

关于今日多次出现“登陆失败，请检查账号/密码, 尝试普通签到”错误，原因未知【已确认cookie和账号相关联】。
若大大有空闲，还望不吝赐教。
PS：operation timed out的解决方案
根据之前的测试得知，是因为开了全局代理，所以无法和pt站取得联系（后来改用rule模式并将站点设置为直连后，可正常连接）更玄学的是，不开代理，和pt站的联系并不一直稳定，而采用rule之后反而更加稳定。

**Comment by azureqaq** [comment]
好的，大概明后天我测试一下，最近刚开学有点活儿。
你太客气了，没准咱俩还是一届的学生呢。我也不是啥大佬，不是计算机的专业，自学的编程，水平不高。互相学习，互相学习。😊

**Comment by azureqaq** [comment]
@zxj1009587922 在无本地cookie时，依旧会出现这种错误提示

```bash
$ /c/Users/user/Desktop/tjuptatt.exe
DEBUG [libs::user] username 签到失败, 1/3, Err: 登陆失败, 请检查账号/密码
DEBUG [libs::user] username 签到失败, 2/3, Err: 登陆失败, 请检查账号/密码
DEBUG [libs::user] username 签到失败, 3/3, Err: 登陆失败, 请检查账号/密码
ERROR [tjuptatt] Error: username 签到失败
```

所以我猜测至少有两种可能：

1. cookie 加载问题 *(可能性很低)*
2. 登录链接已经修改，不再是之前的 `https://tjupt.org/takelogin.php`

以下是此错误部分相关源代码：

```rust
async fn just_login(&self) -> Result<Response> {
    self.client
    	// https://tjupt.org/takelogin.php
        .post(tjupturls::TAKELOGIN)
        .form(&[
            ("username", self.config.id()),
            ("password", self.config.pwd()),
            ("logout", "7days"),
            ("returnto", "attendance.php"),
        ])
        .send()
        .await
        .or(Err(anyhow!("请检查pt服务器状态")))
}
```



```rust
// 这部分代码包含在一个重试循环里

// 首先尝试获取签到页面
// https://www.tjupt.org/attendance.php
let mut res = self.client().get(tjupturls::ATT_HOME).send().await?;

// 如果需要登陆
// 无法通过状态码判断是否重定向，判断链接
if res.url().as_str().contains("login.php") {
    res = self.just_login().await?;
    if res.url().as_str().contains("login.php") {
        return Err(anyhow!("登陆失败, 请检查账号/密码"));
    }
}
```



在tjupt的首页的群聊区发现：

> [1天 7时前] 德莱文Donor @长风万里 测试很到位，一会儿就去堵了
>
> [1天 8时前] 长风万里 浏览器找一个能自定义发送http请求的插件。向北洋域名/takelogin.php发送POST请求，body里选form表单，带两个参数username和password。收到200 和html响应然后就收到新的的cookie了

由此也基本可以断定，原因为第二种。

目前不清楚tjupt以何种方式修改了登录方式，需要进一步的测试。

如果这种 *临时登录* 方式与 *正常登录* 差别较大，可能会需要发布一个 *临时版本*。

同时，我也打算着手 [重构](https://github.com/azureqaq/tjuptatt_release/discussions/4#discussion-4847658) 此项目来解决一些问题，相对于我的空闲时间来说，工作量较大，所以bug修复会比较慢或者非常慢。

非常感谢你对这个小项目的贡献。

**Comment by zxj1009587922** [comment]
好的好的，辛苦大大了。
还请评估工作量和开站日期，若很快开站的话，个人认为并没有必要完成临时版本的重构（虽然有临时版本的话，确实省心不少，嘿嘿）
能帮上忙确实受宠若惊，哈哈哈（毕竟是一个浅浅入门者，感谢大大的倾心交流）
后续也会持续关注此项目（可能也是仅存的可以实现top签到的项目了，哈哈哈，也是因为如此更希望能一直存在）

**Comment by azureqaq** [comment]
@zxj1009587922 十分抱歉，我上一个分析有误。
虽然tjupt更改了登陆方式，但是如果cookie加载成功，那么不应该会去尝试登录。
也就是：只有加载了错误的cookie(或者没cookie可加载)，并且尝试登陆失败，才会出现那种错误信息。

**Comment by azureqaq** [comment]
@zxj1009587922 多亏了你的帮助，原来是一个程序BUG，在一处判断时的失误，导致大多数情况并没有使用本地cookie。现在已经修复。
你可以使用最新版再次尝试。
