### ISSUE TITLE
求问大大，是删库了嘛

### ISSUE THREAD

**Issue by zxj1009587922** [azureqaq/tjuptatt_release#5]
tjuptattendance打开显示404了
是发生啥了嘛😢

**Comment by azureqaq** [comment]
当初这个项目只是拿来练手的，现在加入了 TJUPT 的开发组，就把仓库隐藏了。
你可以在 [这里](https://github.com/orgs/tjupt/people) 查看

**Comment by zxj1009587922** [comment]
> 当初这个项目只是拿来练手的，现在加入了 TJUPT 的开发组，就把仓库隐藏了。 你可以在 [这里](https://github.com/orgs/tjupt/people) 查看

好的好的
